[package]
name = "B2748"
version = "0.1.0"
authors = ["kimhyuk <kimhyuk722@live.co.kr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
